import type {
  ApiAssetLeg,
  ApiBacktestRunDetail,
  ApiBacktestRunTradeAudit,
  ApiCashLeg,
  ApiCompositionDetail,
  ApiOptimizationJobDetail,
} from '../types';
import { clone, createCandidate, createStrategy, nowIso, type DemoState } from './demoStoreShared';

function makePriceSeries(symbol: string, anchorDate: string, prices: number[]): ApiBacktestRunTradeAudit['price_series'] {
  return prices.map((price, index) => {
    const day = new Date(anchorDate);
    day.setUTCDate(day.getUTCDate() + index);
    const close = Number(price.toFixed(2));
    return {
      date: day.toISOString().slice(0, 10),
      open: Number((close - 0.8).toFixed(2)),
      high: Number((close + 1.1).toFixed(2)),
      low: Number((close - 1.4).toFixed(2)),
      close,
      adj_close: close,
      volume: 1_000_000 + index * 80_000 + symbol.length * 10_000,
    };
  });
}

function makeTradeAudit(
  tradeId: string,
  symbol: string,
  segment: string,
  openedAt: string,
  closedAt: string,
  pnlPct: number,
  prices: number[],
  triggerSnapshot: Record<string, import('../types').ParameterValue>,
): ApiBacktestRunTradeAudit {
  const priceSeries = makePriceSeries(symbol, openedAt.slice(0, 10), prices);
  const entryPrice = priceSeries[1]?.close ?? priceSeries[0]?.close ?? 0;
  const exitPrice = priceSeries[priceSeries.length - 2]?.close ?? priceSeries[priceSeries.length - 1]?.close ?? 0;
  const mfe = pnlPct >= 0 ? pnlPct + 2.1 : 1.1;
  const mae = pnlPct >= 0 ? -1.7 : -4.6;
  const commentary =
    pnlPct >= 0
      ? 'Trend capture stayed aligned with the recovered signal stack.'
      : 'Exit lagged the reversal and gave back too much open profit.';
  return {
    trade_id: tradeId,
    symbol,
    segment,
    opened_at: openedAt,
    closed_at: closedAt,
    pnl_pct: pnlPct,
    max_favorable_excursion_pct: Number(mfe.toFixed(2)),
    max_adverse_excursion_pct: Number(mae.toFixed(2)),
    slippage_cost_pct: Number((Math.abs(pnlPct) * 0.08 + 0.12).toFixed(2)),
    commentary,
    price_series: priceSeries,
    trigger_snapshot: triggerSnapshot,
    risk_evaluation: {
      max_favorable_excursion_pct: Number(mfe.toFixed(2)),
      max_adverse_excursion_pct: Number(mae.toFixed(2)),
      mfe_mae_ratio: Number((Math.abs(mfe / Math.min(mae, -0.5))).toFixed(2)),
      slippage_cost_pct: Number((Math.abs(pnlPct) * 0.08 + 0.12).toFixed(2)),
      commentary,
    },
    entry_marker: { date: priceSeries[1]?.date ?? openedAt.slice(0, 10), price: entryPrice },
    exit_marker: { date: priceSeries[priceSeries.length - 2]?.date ?? closedAt.slice(0, 10), price: exitPrice },
    chart_band: { start_date: openedAt, end_date: closedAt, color: pnlPct >= 0 ? 'green' : 'red', pnl_pct: pnlPct },
  };
}

export function createInitialState(): DemoState {
  const qualityMomentum = createStrategy({ id: 'strat-001', name: 'Quality Momentum', latest_optimization_job_id: 'opt-001' });
  const lowVolRotation = createStrategy({
    id: 'strat-002',
    name: 'Low Vol Rotation',
    latest_optimization_job_id: null,
    latest_run_id: null,
    parameters: { lookback_months: 3, skip_recent_months: 1, top_n: 2, weighting_method: 'risk_parity', max_position_pct: 20 },
    current_parameter_version_id: 'strat-002-v1',
    current_parameter_version: 1,
  });

  const candidates = [
    createCandidate(qualityMomentum, { id: 'trial-001', label: '风险收敛版', summary: '收紧持仓广度，并适度拉长回看窗口。', parameter_snapshot: { ...qualityMomentum.parameters, top_n: 6, max_position_pct: 12 }, metrics: { total_return: 14.6, sharpe: 1.31 }, score: 1.34 }, 1),
    createCandidate(qualityMomentum, { id: 'trial-002', label: '波动缓冲版', summary: '提高筛选强度，并增加跳过最近月份。', parameter_snapshot: { ...qualityMomentum.parameters, lookback_months: 9, skip_recent_months: 2 }, metrics: { total_return: 11.2, sharpe: 1.24 }, score: 1.28 }, 2),
    createCandidate(qualityMomentum, { id: 'trial-003', label: '进攻突破版', summary: '扩大持仓篮子以增强上行捕捉，但信号置信度更薄。', parameter_snapshot: { ...qualityMomentum.parameters, top_n: 9, weighting_method: 'volatility_adjusted' }, metrics: { total_return: 5.1, sharpe: 0.92 }, score: 1.11 }, 3),
    createCandidate(qualityMomentum, { id: 'trial-004', label: '过拟合反转版', summary: '样本外表现转弱，建议从实验室中清理。', parameter_snapshot: { ...qualityMomentum.parameters, lookback_months: 2, top_n: 12 }, metrics: { total_return: -4.2, sharpe: -0.18 }, score: -0.22 }, 4),
  ];
  const optimizationJob: ApiOptimizationJobDetail = {
    id: 'opt-001',
    strategy_id: qualityMomentum.id,
    status: 'COMPLETED',
    request: { objective: 'sharpe', base_parameter_version_id: qualityMomentum.current_parameter_version_id },
    summary: { objective: 'sharpe', candidate_count: candidates.length, baseline_parameter_version_id: qualityMomentum.current_parameter_version_id },
    result: { best_candidate_id: candidates[0].id, baseline_parameter_version_id: qualityMomentum.current_parameter_version_id },
    candidates,
    base_parameter_version_id: qualityMomentum.current_parameter_version_id,
    created_at: nowIso(),
    updated_at: nowIso(),
    completed_at: nowIso(),
  };

  const qqqAudit = makeTradeAudit('trade-001', 'QQQ', 'IS', '2025-01-06T09:30:00Z', '2025-01-17T16:00:00Z', 8.4, [402, 405, 408, 411, 414, 416, 418], { momentum_rank: 3, lookback_return_pct: 12.8, portfolio_volatility_pct: 18.4, execution_policy: 'T_CLOSE_TO_T1_OPEN' });
  const aaplAudit = makeTradeAudit('trade-002', 'AAPL', 'OOS', '2025-02-03T09:30:00Z', '2025-02-10T16:00:00Z', -2.1, [188, 190, 187, 185, 184, 183, 186], { momentum_rank: 17, lookback_return_pct: 3.1, portfolio_volatility_pct: 22.6, execution_policy: 'T_CLOSE_TO_T1_OPEN' });
  const run: ApiBacktestRunDetail = {
    id: 'bt-001',
    strategy_id: qualityMomentum.id,
    status: 'COMPLETED_WITH_WARNINGS',
    metrics: { total_return: 18.4, sharpe: 1.18, max_drawdown: -6.4 },
    chart_series: [{ trade_date: '2025-01-02', equity: 100, benchmark: 100, drawdown: 0, is_oos: false }, { trade_date: '2025-01-10', equity: 106, benchmark: 102, drawdown: -1.2, is_oos: false }, { trade_date: '2025-02-06', equity: 111, benchmark: 104, drawdown: -3.4, is_oos: true }, { trade_date: '2025-02-28', equity: 118.4, benchmark: 108.1, drawdown: -2.6, is_oos: true }],
    monthly_returns: [{ month: '2025-01', return_pct: 6.2, segment: 'IS' }, { month: '2025-02', return_pct: 4.7, segment: 'OOS' }],
    trade_details: [{ trade_date: '2025-01-06', symbol: 'QQQ', side: 'BUY', quantity: 100, price: 405, notional: 40500, pnl_pct: 8.4, signal: 'Momentum breakout' }, { trade_date: '2025-02-03', symbol: 'AAPL', side: 'BUY', quantity: 80, price: 190, notional: 15200, pnl_pct: -2.1, signal: 'Weak quality follow-through' }],
    configuration: { oos_start_date: '2025-02-01', execution_policy: 'T_CLOSE_TO_T1_OPEN' },
    parameter_snapshot: qualityMomentum.parameters ?? {},
    snapshot_summary: { dataset_snapshot_id: 'dataset-20250330', universe_snapshot_id: 'universe-20250330' },
    data_segment_type: 'FULL',
    parameter_version_id: qualityMomentum.current_parameter_version_id,
    request: { start_date: '2025-01-02', end_date: '2025-02-28', fee_bps: 1.5, slippage_bps: 2.5, execution_policy: 'T_CLOSE_TO_T1_OPEN' },
    is_permanent: false,
    source_run_id: null,
    trade_audit_items: [clone({ trade_id: qqqAudit.trade_id, symbol: qqqAudit.symbol, segment: qqqAudit.segment, opened_at: qqqAudit.opened_at, closed_at: qqqAudit.closed_at, pnl_pct: qqqAudit.pnl_pct, max_favorable_excursion_pct: qqqAudit.max_favorable_excursion_pct, max_adverse_excursion_pct: qqqAudit.max_adverse_excursion_pct, slippage_cost_pct: qqqAudit.slippage_cost_pct, commentary: qqqAudit.commentary }), clone({ trade_id: aaplAudit.trade_id, symbol: aaplAudit.symbol, segment: aaplAudit.segment, opened_at: aaplAudit.opened_at, closed_at: aaplAudit.closed_at, pnl_pct: aaplAudit.pnl_pct, max_favorable_excursion_pct: aaplAudit.max_favorable_excursion_pct, max_adverse_excursion_pct: aaplAudit.max_adverse_excursion_pct, slippage_cost_pct: aaplAudit.slippage_cost_pct, commentary: aaplAudit.commentary })],
    trade_audit: [qqqAudit, aaplAudit],
    analysis: {
      subtitle: '测试集仍然领先基准，但近期回撤修复偏慢，优先检查样本外交易质量。',
      kpi_cards: [
        {
          key: 'total_return',
          label: '总收益',
          primary_text: '+18.4%',
          trend_direction: 'up',
          trend_text: '↑ 跑赢基准 8.1%',
          compare_text: '基准: +10.3% | 差值: +8.1%',
          insight_text: '收益表现稳定，建议继续监控 Beta 暴露。',
          insight_tone: 'positive',
          state: 'healthy',
        },
        {
          key: 'sharpe',
          label: '夏普比率',
          primary_text: '1.18',
          trend_direction: 'up',
          trend_text: '↑ 高于基准 0.37',
          compare_text: '基准: 0.81 | 差值: +0.37',
          insight_text: '风险回报领先，但需防止样本外 Sharpe 回落。',
          insight_tone: 'positive',
          state: 'healthy',
        },
        {
          key: 'max_drawdown',
          label: '最大回撤',
          primary_text: '-6.4%',
          trend_direction: 'up',
          trend_text: '↓ 优于基准 5.2%',
          compare_text: '基准: -11.6% | 差值: +5.2%',
          insight_text: '风控优于基准，仍需确认回撤恢复路径。',
          insight_tone: 'neutral',
          state: 'watch',
        },
        {
          key: 'rolling_252_return',
          label: '最新 252 日滚动收益',
          primary_text: '+17.1%',
          trend_direction: 'up',
          trend_text: '↑ 高于基准 4.8%',
          compare_text: '基准: +12.3% | 差值: +4.8%',
          insight_text: '近期优势明显，但建议扩大样本窗口再确认。',
          insight_tone: 'warning',
          state: 'watch',
        },
        {
          key: 'trade_count',
          label: '交易数',
          primary_text: '2',
          trend_direction: 'flat',
          trend_text: '训练集 1 / 测试集 1',
          compare_text: '训练集: 1 | 测试集: 1',
          insight_text: '测试集样本偏少，警惕随机性导致的过拟合。',
          insight_tone: 'warning',
          state: 'watch',
        },
      ],
      decision_rail: {
        score: 67,
        summary: '测试集方向仍在，但要先核查近期退化是否来自个别交易。',
        items: [
          {
            key: 'result',
            title: '结果判断',
            body: '测试集仍跑赢基准，方向保持成立。',
            tone: 'positive',
          },
          {
            key: 'risk',
            title: '风险判断',
            body: '样本外回撤恢复偏慢，需要结合成交证据定位问题区段。',
            tone: 'warning',
          },
          {
            key: 'next_action',
            title: '下一步动作',
            body: '优先回看测试集交易，再决定是否进入新一轮寻优。',
            tone: 'neutral',
          },
        ],
      },
    },
  };

  const assetLegs: ApiAssetLeg[] = [
    {
      id: 'asset-leg-spy-core',
      name: '美股核心 Beta',
      symbol: 'SPY',
      asset_kind: 'equity_index',
      source_snapshot_id: 'ds-price',
      source_provider: 'yahoo',
      freeze_mode: 'snapshot_locked',
      notes: '用于组合中的权益 Beta 锚点。',
      summary: {
        issuer: 'State Street',
        role: 'beta_anchor',
        latest_total_return_pct: 6.4,
      },
      status: 'ACTIVE',
      eligibility_summary: {
        snapshot_ref: 'ds-price',
        freeze_mode: 'snapshot_locked',
        reference_count: 1,
      },
      attribute_tags: ['asset', 'equity_index', 'low_correlation'],
      allowed_actions: ['edit_leg_definition', 'open_composition_workbench'],
      created_at: nowIso(),
      updated_at: nowIso(),
    },
    {
      id: 'asset-leg-ust10y',
      name: '美债 10Y',
      symbol: 'UST10Y',
      asset_kind: 'bond_government',
      source_snapshot_id: 'bond-ust-10y',
      source_provider: 'fmp',
      freeze_mode: 'eod_snapshot',
      notes: '利率对冲与回撤缓冲腿。',
      summary: {
        ytm_pct: 4.2,
        duration_years: 8.6,
        accrued_interest_mode: 'daily',
      },
      status: 'ACTIVE',
      eligibility_summary: {
        snapshot_ref: 'bond-ust-10y',
        freeze_mode: 'eod_snapshot',
        reference_count: 2,
      },
      attribute_tags: ['asset', 'bond_government', 'duration_carry', 'low_correlation'],
      allowed_actions: ['edit_leg_definition', 'open_composition_workbench'],
      created_at: nowIso(),
      updated_at: nowIso(),
    },
  ];

  const cashLegs: ApiCashLeg[] = [
    {
      id: 'cash-leg-buffer-core',
      name: '现金缓冲',
      cash_rule_kind: 'buffer',
      buffer_bps: 12,
      yield_source: 'SOFR',
      freeze_mode: 'rule_locked',
      notes: '用于再平衡与交易成本缓冲。',
      summary: {
        reserve_target_pct: 8,
        carry_label: 'SOFR - 10bps',
      },
      status: 'ACTIVE',
      attribute_tags: ['cash', 'buffer', 'liquidity'],
      allowed_actions: ['edit_leg_definition', 'open_composition_workbench'],
      created_at: nowIso(),
      updated_at: nowIso(),
    },
  ];

  const composition: ApiCompositionDetail = {
    id: 'comp-001',
    name: '全天候研究组合',
    description: '策略腿、债券腿与现金腿的第一拍组合验证样本。',
    status: 'ACTIVE',
    status_label: '运行中',
    created_at: nowIso(),
    updated_at: nowIso(),
    benchmark_definition: {
      label: '60/40 基准',
      symbol: '6040',
      source: 'custom_blend',
    },
    rebalance_frequency: 'quarterly',
    cost_policy: {
      expense_ratio_bps: 18,
      turnover_budget_bps: 12,
      trade_cost_bps: 8,
      notes: '按季度再平衡估算。',
    },
    hero_summary: {
      title: '全天候研究组合',
      subtitle: '权益 Beta、利率对冲与现金缓冲的组合验证样本。',
      status: 'ACTIVE',
      status_label: '运行中',
      benchmark_label: '60/40 基准',
      leg_count: 4,
      composition_score: 82,
      updated_at: nowIso(),
    },
    kpis: [
      { key: 'annualized_return', label: '年化收益', value: 9.8, unit: '%', tone: 'positive', detail: '超基准 2.1%' },
      { key: 'max_drawdown', label: '最大回撤', value: -7.4, unit: '%', tone: 'warning', detail: '回撤恢复 41 天' },
      { key: 'sharpe', label: '夏普比率', value: 1.24, tone: 'positive', detail: '波动控制优于基准' },
      { key: 'sortino', label: '索提诺比率', value: 1.61, tone: 'positive', detail: '下行波动受控' },
      { key: 'rebalance_cost', label: '再平衡成本', value: 12, unit: 'bps', tone: 'neutral', detail: '季度窗口估算' },
      { key: 'leg_count', label: '腿数量', value: 4, tone: 'neutral', detail: '策略 / 资产 / 现金并存' },
      { key: 'correlation_flag', label: '高相关提醒', value: 1, tone: 'warning', detail: '一组资产腿相关性偏高' },
    ],
    weight_summary: {
      total_weight_pct: 100,
      target_weight_pct: 100,
      residual_weight_pct: 0,
      locked_weight_pct: 58,
      unlocked_weight_pct: 42,
      within_tolerance: true,
    },
    normalized_legs: [
      {
        id: 'strategy_leg::strat-001::strat-001-v2',
        leg_kind: 'strategy',
        source_ref_id: 'strategy_leg::strat-001::strat-001-v2',
        source_ref_type: 'strategy_projection',
        display_name: 'Quality Momentum',
        weight_pct: 32,
        weight_locked: false,
        ordering: 1,
        version_label: 'v2',
        proof_label: 'bt-001',
        status: 'READY',
        status_label: '可用',
        attribute_tags: ['strategy', 'momentum', 'recent_strength'],
        reference_summary: 'Used in 1 saved composition',
        config: { strategy_id: 'strat-001', parameter_version_id: 'strat-001-v2' },
        allowed_actions: ['open_strategy_detail', 'open_composition_workbench'],
      },
      {
        id: 'strategy_leg::strat-002::strat-002-v1',
        leg_kind: 'strategy',
        source_ref_id: 'strategy_leg::strat-002::strat-002-v1',
        source_ref_type: 'strategy_projection',
        display_name: 'Low Vol Rotation',
        weight_pct: 18,
        weight_locked: false,
        ordering: 2,
        version_label: 'v1',
        proof_label: '待补回测',
        status: 'NEEDS_RUN',
        status_label: '待回测',
        attribute_tags: ['strategy', 'defensive', 'low_correlation'],
        reference_summary: 'Not used in saved compositions yet',
        config: { strategy_id: 'strat-002', parameter_version_id: 'strat-002-v1' },
        allowed_actions: ['run_backtest', 'open_strategy_detail'],
      },
      {
        id: 'asset-leg-ust10y',
        leg_kind: 'asset',
        source_ref_id: 'asset-leg-ust10y',
        source_ref_type: 'asset_definition',
        display_name: '美债 10Y',
        weight_pct: 30,
        weight_locked: true,
        ordering: 3,
        version_label: 'UST10Y',
        proof_label: 'bond-ust-10y',
        status: 'ACTIVE',
        status_label: '已入库',
        attribute_tags: ['asset', 'bond_government', 'low_correlation'],
        reference_summary: 'Used in 2 saved compositions',
        config: { snapshot_id: 'bond-ust-10y', duration_years: 8.6 },
        allowed_actions: ['edit_leg_definition', 'open_composition_workbench'],
      },
      {
        id: 'cash-leg-buffer-core',
        leg_kind: 'cash',
        source_ref_id: 'cash-leg-buffer-core',
        source_ref_type: 'cash_definition',
        display_name: '现金缓冲',
        weight_pct: 20,
        weight_locked: true,
        ordering: 4,
        version_label: 'buffer',
        proof_label: 'SOFR',
        status: 'ACTIVE',
        status_label: '已入库',
        attribute_tags: ['cash', 'buffer', 'liquidity'],
        reference_summary: 'Used in 1 saved composition',
        config: { buffer_bps: 12 },
        allowed_actions: ['edit_leg_definition', 'open_composition_workbench'],
      },
    ],
    returns_preview: [
      { label: '2025-11', date: '2025-11-30', portfolio_return_pct: 1.1, cumulative_return_pct: 1.1 },
      { label: '2025-12', date: '2025-12-31', portfolio_return_pct: 0.8, cumulative_return_pct: 1.9 },
      { label: '2026-01', date: '2026-01-31', portfolio_return_pct: 1.6, cumulative_return_pct: 3.5 },
      { label: '2026-02', date: '2026-02-28', portfolio_return_pct: -0.4, cumulative_return_pct: 3.1 },
      { label: '2026-03', date: '2026-03-31', portfolio_return_pct: 2.4, cumulative_return_pct: 5.5 },
      { label: '2026-04', date: '2026-04-30', portfolio_return_pct: 1.9, cumulative_return_pct: 7.4 },
    ],
    benchmark_series: [
      { label: '2025-11', date: '2025-11-30', benchmark_return_pct: 0.9, cumulative_return_pct: 0.9 },
      { label: '2025-12', date: '2025-12-31', benchmark_return_pct: 0.6, cumulative_return_pct: 1.5 },
      { label: '2026-01', date: '2026-01-31', benchmark_return_pct: 1.1, cumulative_return_pct: 2.6 },
      { label: '2026-02', date: '2026-02-28', benchmark_return_pct: -0.9, cumulative_return_pct: 1.7 },
      { label: '2026-03', date: '2026-03-31', benchmark_return_pct: 1.6, cumulative_return_pct: 3.3 },
      { label: '2026-04', date: '2026-04-30', benchmark_return_pct: 1.2, cumulative_return_pct: 4.5 },
    ],
    spread_series: [
      { label: '2025-11', date: '2025-11-30', spread_pct: 0.2 },
      { label: '2025-12', date: '2025-12-31', spread_pct: 0.3 },
      { label: '2026-01', date: '2026-01-31', spread_pct: 0.9 },
      { label: '2026-02', date: '2026-02-28', spread_pct: 1.4 },
      { label: '2026-03', date: '2026-03-31', spread_pct: 2.2 },
      { label: '2026-04', date: '2026-04-30', spread_pct: 2.9 },
    ],
    rebalance_markers: [
      { label: '季度再平衡', date: '2026-01-31', index: 2 },
      { label: '季度再平衡', date: '2026-04-30', index: 5 },
    ],
    correlation_matrix: [
      { x_key: 'qm', y_key: 'qm', correlation: 1 },
      { x_key: 'qm', y_key: 'lv', correlation: 0.34 },
      { x_key: 'qm', y_key: 'bond', correlation: -0.18 },
      { x_key: 'qm', y_key: 'cash', correlation: 0.05 },
      { x_key: 'lv', y_key: 'lv', correlation: 1 },
      { x_key: 'lv', y_key: 'bond', correlation: 0.22 },
      { x_key: 'lv', y_key: 'cash', correlation: 0.09 },
      { x_key: 'bond', y_key: 'bond', correlation: 1 },
      { x_key: 'bond', y_key: 'cash', correlation: 0.42 },
      { x_key: 'cash', y_key: 'cash', correlation: 1 },
    ],
    risk_contribution_preview: [
      { leg_id: 'strategy_leg::strat-001::strat-001-v2', label: 'Quality Momentum', weight_pct: 32, volatility_pct: 21, contribution_pct: 44 },
      { leg_id: 'strategy_leg::strat-002::strat-002-v1', label: 'Low Vol Rotation', weight_pct: 18, volatility_pct: 11, contribution_pct: 14 },
      { leg_id: 'asset-leg-ust10y', label: '美债 10Y', weight_pct: 30, volatility_pct: 8, contribution_pct: 24 },
      { leg_id: 'cash-leg-buffer-core', label: '现金缓冲', weight_pct: 20, volatility_pct: 1.5, contribution_pct: 4 },
    ],
    maintenance_cost_summary: {
      expense_ratio_bps: 18,
      turnover_budget_bps: 12,
      trade_cost_bps: 8,
      total_estimated_bps: 38,
      notes: ['季度再平衡窗口预计单次损耗 12 bps', '现金腿承担缓冲作用'],
    },
    scenario_summary: {
      base_case: { label: '常态波动', expected_drawdown_pct: -7.4 },
      stress_case: { label: '2022 加息压力', expected_drawdown_pct: -11.2 },
      dispersion_note: '策略腿与债券腿在加息期相关性抬升，需要关注再平衡窗口。',
    },
    source_evidence: [
      {
        id: 'freeze-001',
        leg_id: 'strategy_leg::strat-001::strat-001-v2',
        display_name: 'Quality Momentum',
        freeze_ref_type: 'strategy_projection',
        freeze_ref_id: 'strat-001-v2',
        freeze_hash: 'c0a1f8',
        captured_at: nowIso(),
        snapshot: { run_id: 'bt-001', parameter_version_id: 'strat-001-v2' },
      },
      {
        id: 'freeze-002',
        leg_id: 'asset-leg-ust10y',
        display_name: '美债 10Y',
        freeze_ref_type: 'asset_snapshot',
        freeze_ref_id: 'bond-ust-10y',
        freeze_hash: 'b9d02e',
        captured_at: nowIso(),
        snapshot: { snapshot_id: 'bond-ust-10y', ytm_pct: 4.2, duration_years: 8.6 },
      },
    ],
    composition_score: {
      score: 82,
      verdict: '成立',
      factors: [
        { key: 'diversification', label: '分散度', score: 84, detail: '权益、利率与现金三类腿并存。', tone: 'positive' },
        { key: 'evidence', label: '来源可信度', score: 88, detail: '关键来源均有快照或回测证明。', tone: 'positive' },
        { key: 'cost', label: '成本控制', score: 76, detail: '季度再平衡仍有 38 bps 年化维护成本。', tone: 'warning' },
        { key: 'alpha', label: '收益增强', score: 80, detail: '相对 60/40 基准保持稳定超额。', tone: 'positive' },
      ],
    },
    latest_activity_label: '2026-04-22 更新',
    deep_link_actions: [
      'open_composition_workbench',
      'open_leg_inventory',
      'inspect_source_evidence',
      'refresh_snapshots',
    ],
  };

  return {
    strategies: [qualityMomentum, lowVolRotation],
    assetLegs,
    cashLegs,
    compositions: [composition],
    factors: [],
    optimizationJobs: [optimizationJob],
    sessions: [],
    runs: [run],
    tradeAudits: { 'bt-001': { [qqqAudit.trade_id]: qqqAudit, [aaplAudit.trade_id]: aaplAudit } },
    promoteConflicts: new Set<string>(),
  };
}
